//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//
//     对此文件的更改可能导致不正确的行为，并在以下条件下丢失:
//     代码重新生成。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeInfo
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://server.webservice.service.mgw.mascloud.umpay.com/", ConfigurationName="WeInfo.WsSmsService")]
    public interface WsSmsService
    {
        
        // CODEGEN: 正在生成消息协定，因为命名空间  的元素名称 arg0 未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://server.webservice.service.mgw.mascloud.umpay.com/WsSmsService/sendSmsReque" +
            "st", ReplyAction="http://server.webservice.service.mgw.mascloud.umpay.com/WsSmsService/sendSmsRespo" +
            "nse")]
        WeInfo.sendSmsResponse sendSms(WeInfo.sendSmsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://server.webservice.service.mgw.mascloud.umpay.com/WsSmsService/sendSmsReque" +
            "st", ReplyAction="http://server.webservice.service.mgw.mascloud.umpay.com/WsSmsService/sendSmsRespo" +
            "nse")]
        System.Threading.Tasks.Task<WeInfo.sendSmsResponse> sendSmsAsync(WeInfo.sendSmsRequest request);
        
        // CODEGEN: 正在生成消息协定，因为命名空间  的元素名称 arg0 未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://server.webservice.service.mgw.mascloud.umpay.com/WsSmsService/sendTplSmsRe" +
            "quest", ReplyAction="http://server.webservice.service.mgw.mascloud.umpay.com/WsSmsService/sendTplSmsRe" +
            "sponse")]
        WeInfo.sendTplSmsResponse sendTplSms(WeInfo.sendTplSmsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://server.webservice.service.mgw.mascloud.umpay.com/WsSmsService/sendTplSmsRe" +
            "quest", ReplyAction="http://server.webservice.service.mgw.mascloud.umpay.com/WsSmsService/sendTplSmsRe" +
            "sponse")]
        System.Threading.Tasks.Task<WeInfo.sendTplSmsResponse> sendTplSmsAsync(WeInfo.sendTplSmsRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class sendSmsRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="sendSms", Namespace="http://server.webservice.service.mgw.mascloud.umpay.com/", Order=0)]
        public WeInfo.sendSmsRequestBody Body;
        
        public sendSmsRequest()
        {
        }
        
        public sendSmsRequest(WeInfo.sendSmsRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class sendSmsRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string arg0;
        
        public sendSmsRequestBody()
        {
        }
        
        public sendSmsRequestBody(string arg0)
        {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class sendSmsResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="sendSmsResponse", Namespace="http://server.webservice.service.mgw.mascloud.umpay.com/", Order=0)]
        public WeInfo.sendSmsResponseBody Body;
        
        public sendSmsResponse()
        {
        }
        
        public sendSmsResponse(WeInfo.sendSmsResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class sendSmsResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public sendSmsResponseBody()
        {
        }
        
        public sendSmsResponseBody(string @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class sendTplSmsRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="sendTplSms", Namespace="http://server.webservice.service.mgw.mascloud.umpay.com/", Order=0)]
        public WeInfo.sendTplSmsRequestBody Body;
        
        public sendTplSmsRequest()
        {
        }
        
        public sendTplSmsRequest(WeInfo.sendTplSmsRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class sendTplSmsRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string arg0;
        
        public sendTplSmsRequestBody()
        {
        }
        
        public sendTplSmsRequestBody(string arg0)
        {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class sendTplSmsResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="sendTplSmsResponse", Namespace="http://server.webservice.service.mgw.mascloud.umpay.com/", Order=0)]
        public WeInfo.sendTplSmsResponseBody Body;
        
        public sendTplSmsResponse()
        {
        }
        
        public sendTplSmsResponse(WeInfo.sendTplSmsResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class sendTplSmsResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public sendTplSmsResponseBody()
        {
        }
        
        public sendTplSmsResponseBody(string @return)
        {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface WsSmsServiceChannel : WeInfo.WsSmsService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class WsSmsServiceClient : System.ServiceModel.ClientBase<WeInfo.WsSmsService>, WeInfo.WsSmsService
    {
        
        /// <summary>
        /// 实现此分部方法，配置服务终结点。
        /// </summary>
        /// <param name="serviceEndpoint">要配置的终结点</param>
        /// <param name="clientCredentials">客户端凭据</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public WsSmsServiceClient() : 
                base(WsSmsServiceClient.GetDefaultBinding(), WsSmsServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.WsSmsServicePort.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WsSmsServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(WsSmsServiceClient.GetBindingForEndpoint(endpointConfiguration), WsSmsServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WsSmsServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(WsSmsServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WsSmsServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(WsSmsServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WsSmsServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WeInfo.sendSmsResponse WeInfo.WsSmsService.sendSms(WeInfo.sendSmsRequest request)
        {
            return base.Channel.sendSms(request);
        }
        
        public string sendSms(string arg0)
        {
            WeInfo.sendSmsRequest inValue = new WeInfo.sendSmsRequest();
            inValue.Body = new WeInfo.sendSmsRequestBody();
            inValue.Body.arg0 = arg0;
            WeInfo.sendSmsResponse retVal = ((WeInfo.WsSmsService)(this)).sendSms(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WeInfo.sendSmsResponse> WeInfo.WsSmsService.sendSmsAsync(WeInfo.sendSmsRequest request)
        {
            return base.Channel.sendSmsAsync(request);
        }
        
        public System.Threading.Tasks.Task<WeInfo.sendSmsResponse> sendSmsAsync(string arg0)
        {
            WeInfo.sendSmsRequest inValue = new WeInfo.sendSmsRequest();
            inValue.Body = new WeInfo.sendSmsRequestBody();
            inValue.Body.arg0 = arg0;
            return ((WeInfo.WsSmsService)(this)).sendSmsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WeInfo.sendTplSmsResponse WeInfo.WsSmsService.sendTplSms(WeInfo.sendTplSmsRequest request)
        {
            return base.Channel.sendTplSms(request);
        }
        
        public string sendTplSms(string arg0)
        {
            WeInfo.sendTplSmsRequest inValue = new WeInfo.sendTplSmsRequest();
            inValue.Body = new WeInfo.sendTplSmsRequestBody();
            inValue.Body.arg0 = arg0;
            WeInfo.sendTplSmsResponse retVal = ((WeInfo.WsSmsService)(this)).sendTplSms(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WeInfo.sendTplSmsResponse> WeInfo.WsSmsService.sendTplSmsAsync(WeInfo.sendTplSmsRequest request)
        {
            return base.Channel.sendTplSmsAsync(request);
        }
        
        public System.Threading.Tasks.Task<WeInfo.sendTplSmsResponse> sendTplSmsAsync(string arg0)
        {
            WeInfo.sendTplSmsRequest inValue = new WeInfo.sendTplSmsRequest();
            inValue.Body = new WeInfo.sendTplSmsRequestBody();
            inValue.Body.arg0 = arg0;
            return ((WeInfo.WsSmsService)(this)).sendTplSmsAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.WsSmsServicePort))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("找不到名称为“{0}”的终结点。", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.WsSmsServicePort))
            {
                return new System.ServiceModel.EndpointAddress("http://112.35.10.201:1999/smsservice");
            }
            throw new System.InvalidOperationException(string.Format("找不到名称为“{0}”的终结点。", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return WsSmsServiceClient.GetBindingForEndpoint(EndpointConfiguration.WsSmsServicePort);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return WsSmsServiceClient.GetEndpointAddress(EndpointConfiguration.WsSmsServicePort);
        }
        
        public enum EndpointConfiguration
        {
            
            WsSmsServicePort,
        }
    }
}
